[platformio]
default_envs = ArduinoISP

[env]
platform = atmelavr
board = attiny85
framework = arduino
board_build.f_cpu = 8000000UL
extra_scripts = post:extra_script.py
upload_speed = 19200
upload_flags =
    -C${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p$BOARD_MCU
    -P$UPLOAD_PORT
    -b$UPLOAD_SPEED
    -c$UPLOAD_PROTOCOL
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i -U lfuse:w:0xF1:m

[env:ArduinoISP]
upload_protocol = stk500v1